INSERT INTO "USER" (
                ID,
                USERNAME,
                PASSWORD,
                ROLE,
                ISACTIVE
        )
VALUES (
                1,
                'john@example.mis.com',
                'changeme',
                'administrator',
                true
        ),
        (
                2,
                'chris@example.mis.com',
                'secret',
                'guest',
                true
        ),
        (
                3,
                'maria@example.mis.com',
                'guess',
                'reader',
                true
        ),
        (
                4,
                'hans@example.mis.com',
                'devote',
                'librarian',
                true
        ),
        (
                5,
                'alice@example.mis.com',
                'kitchen',
                'officer',
                true
        ),
        (
                6,
                'morse@example.mis.com',
                'pivot',
                'technician',
                true
        ),
        (
                7,
                'kennedy@example.mis.com',
                'forgetme',
                'merchandiser',
                true
        ),
        (
                8,
                'nice@example.mis.com',
                'expose',
                'storekeeper',
                true
        ),
        (
                9,
                'adam@example.mis.com',
                'madeus',
                'vendor',
                true
        )